### ISSUE TITLE
Download arkade in this action so that setup-arkade isn't required

### ISSUE THREAD

**Issue by alexellis** [alexellis/arkade-get#38]
Before:

```
    - uses: alexellis/setup-arkade@v2
    - uses: alexellis/arkade-get@master
      with:
        kubectl: latest
        faas-cli: 0.14.10
    - name: check for faas-cli
      run: |
        faas-cli version
```

After:

```
    - uses: alexellis/arkade-get@master
      with:
        kubectl: latest
        faas-cli: 0.14.10
    - name: check for faas-cli
      run: |
        faas-cli version
```

Bear in mind that the bash script installer for arkade is OS and arch aware, and this needs to be kept for the arkade-get action too. At least for Linux aarch64 and amd64.

https://github.com/alexellis/arkade/blob/master/get.sh
